version: '3.9'

services:
  api:
    ports:
      # Exposes application port.
    - "8000:8000"
    build:
      target: dev
    volumes:
      # Adds current directory as volume.
    - .:/app/src/
    environment:
      # Enables autoreload.
      NUITINFO_RELOAD: "True"
  app:
    build:
      context: .
      dockerfile: ./deploy/frontend/Dockerfile.react.dev
    image: app:alpha-sexinfo

  nginx:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.nginx.dev
    image: nginx:alpha-sexinfo
    ports:
      # Exposes nginx port.
    - "80:80"
    depends_on:
      # Waits for api to be ready.
    - api
