"""Add column inventory to user

Revision ID: aa1712c6035f
Revises: f1438d138814
Create Date: 2023-12-07 20:31:43.209243

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "aa1712c6035f"
down_revision = "f1438d138814"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("inventory", sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "inventory")
    # ### end Alembic commands ###
