"""empty message

Revision ID: f2136eea2668
Revises: aa1712c6035f
Create Date: 2023-12-07 21:53:10.335419

"""

# revision identifiers, used by Alembic.
revision = "f2136eea2668"
down_revision = "aa1712c6035f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
