"""empty message

Revision ID: d15278226248
Revises: fbbeeac031c8
Create Date: 2023-12-08 00:04:04.854630

"""

# revision identifiers, used by Alembic.
revision = "d15278226248"
down_revision = "fbbeeac031c8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
